
<?php // cart

$order=$this->getOrder();
$shipping_address=$this->getShippingAddress();

?>
<script type="text/javascript">

  var _gaq = _gaq || [];
  _gaq.push(['_setAccount', <?php echo $this->getAnalyticsAccount(); ?>]);
  _gaq.push(['_trackPageview']);
  _gaq.push(['_addTrans',
    '<?php echo $order->getIncrementId()?>',           // transaction ID - required
    '<?php echo $this->getStoreName();?>',  // affiliation or store name
    '<?php echo $order->getGrandTotal()?>',          // total - required
    '<?php echo $order->getTaxAmount()?>',           // tax
    '<?php echo $order->getShippingAmount()?>',              // shipping
    '<?php echo $shipping_address->getCity()?>',       // city
    '<?php echo $shipping_address->getRegion()?>',     // state or province
    'IT'             // country
  ]);
<?php foreach($order->getAllItems() as $item):?>
   // add item might be called for every item in the shopping cart
   // where your ecommerce engine loops through each item in the cart and
   // prints out _addItem for each
  _gaq.push(['_addItem',
    '<?php echo $order->getIncrementId()?>',           // transaction ID - required
    '<?php echo $item->getSku()?>',           // SKU/code - required
    '<?php echo $item->getName()?>',        // product name
    '<?php ?>',   // category or variation
    '<?php echo $item->getPriceInclTax()?>',          // unit price - required
    '<?php echo $item->getQtyOrdered()?>'               // quantity - required
  ]);
<?php endforeach;?>
  _gaq.push(['_trackTrans']); //submits transaction to the Analytics servers

  (function() {
    var ga = document.createElement('script'); ga.type = 'text/javascript'; ga.async = true;
    ga.src = ('https:' == document.location.protocol ? 'https://ssl' : 'http://www') + '.google-analytics.com/ga.js';
    var s = document.getElementsByTagName('script')[0]; s.parentNode.insertBefore(ga, s);
  })();

</script>




